### ISSUE TITLE
Deployment Docker on Synology

### ISSUE THREAD

**Issue by kinderwerk** [gitroomhq/postiz-docs#30]
Hey guys, I'm not ready to test Postiz yet, but during the installation via Docker Compose on my Synology NAS, I've encountered two issues.

Port 5000 is the default for DSM HTTP access, and 5432 is already in use for Postgres on the NAS itself. Of course, both can be resolved by using different ports. But I just wanted to document this for reference. :-)

**Comment by jamesread** [comment]
Hey @kinderwerk , we've just had a couple of folks on Discord get Postiz working on synology boxes (maybe you are one of the people we've been talking to on Discord!).

We've updated the docs to remove port 5432 (for postgres) externally from the Docker compose - it doens't need to listen externally, so that just removes one conflict. The Postiz database will still listen on port 5432, but it's in a container, and only accessed on the Postiz network, so it won't conflict with synology's Postgres.

We've not had an issue with the port 5000 conflict, but this is just the frontend port for Postiz, so this can really be bound to any available external port that you like. Most of the time your reverse proxy will "hide" this anyway. 

Let us know if you any any issues, or need help getting Postiz up and running!

**Comment by jamesread** [comment]
Closing due to no reply in a month. If you still need help with getting Postiz going on Synology, please let us know - reopen an issue on the main Postiz repo, or jump on Discord is best.
