### ISSUE TITLE
Feedback for “Linkedin”

### ISSUE THREAD

**Issue by zenprocess** [gitroomhq/postiz-docs#6]
this doesn't see migrated to the v2 api?

**Comment by jamesread** [comment]
Hey @zenprocess , it's taken me a while to take a look at this, but indeed I've been having some problems with the LinkedIn API on my installation (most notably, not being able to get "advertising API" access). I raised this in https://github.com/gitroomhq/postiz-app/issues/428 . 

All the API calls in the LinkedIn provider do actually use v2 URLs, but I believe the /v2/me calls are deprecated in favour of /v2/userinfo ( see the issue description above ). 

I'm probably going to submit a branch soon for this, because I need to remove calls to /v2/me to get LinkedIn working, but I'll need to chat with @nevo-david before merging that into main. 

Let's continue this discussion on https://github.com/gitroomhq/postiz-app/issues/428 - as it's not really a docs issue.
